/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p9-g859cb6c9
 *
 * Project: 'business_card.Release+nRF52832_xxAA' 
 * Target:  'Release+nRF52832_xxAA' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "nrf.h"



#endif /* RTE_COMPONENTS_H */
