/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'business_card.Debug+nRF52832_xxAA' 
 * Target:  'Debug+nRF52832_xxAA' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "nrf.h"



#endif /* RTE_COMPONENTS_H */
